### ISSUE TITLE
Cannot convert json to rstb

### ISSUE THREAD

**Issue by Kissh2021** [NiceneNerd/Hyrule-Builder#5]
I don't know why... But the "json_to_rstb" don't work for me, i son't know if it's normal or not.

PS C:\Users\valen\Desktop\Zelda Modding\Mods> json_to_rstb -o table.rsizetable merged.json
Traceback (most recent call last):
  File "c:\users\valen\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\valen\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\valen\AppData\Local\Programs\Python\Python37\Scripts\json_to_rstb.exe\__main__.py", line 7, in <module>
  File "c:\users\valen\appdata\local\programs\python\python37\lib\site-packages\hyrule_builder\rstb_main.py", line 43, in json_to_rstb
    table = builder.load_rstb(be=args.be, file=in_file)
AttributeError: module 'hyrule_builder.builder' has no attribute 'load_rstb'

**Comment by Kissh2021** [comment]
After many tries on python 3.7, i tried on python 3.9 and...

`C:\Users\valen\Desktop\Zelda Modding\Mods>json_to_rstb -o jaj.rsizetable  merged.json
Traceback (most recent call last):
  File "c:\users\valen\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\valen\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\valen\AppData\Local\Programs\Python\Python39\Scripts\json_to_rstb.exe\__main__.py", line 7, in <module>
  File "c:\users\valen\appdata\local\programs\python\python39\lib\site-packages\hyrule_builder\rstb_main.py", line 43, in json_to_rstb
    table = builder.load_rstb(be=args.be, file=in_file)
  File "c:\users\valen\appdata\local\programs\python\python39\lib\site-packages\hyrule_builder\builder.py", line 65, in load_rstb
    ref_contents = json.loads(file.read_text(), encoding="utf-8")
  File "c:\users\valen\appdata\local\programs\python\python39\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

**Comment by NiceneNerd** [comment]
What version do you have?
