### ISSUE TITLE
Actor Info entries not found?

### ISSUE THREAD

**Issue by ArchLeaders** [NiceneNerd/Hyrule-Builder#6]
I'm am getting a **File Not Found** error when unbuilding actors. 

The most recent case being **AirWallcreature.sbactorpack** when unbuilding I am consistently getting the following error.

```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\hyrule_builder.exe\__main__.py", line 7, in <module>
  File "c:\python\lib\site-packages\hyrule_builder\__main__.py", line 91, in main
    args.func(args)
  File "c:\python\lib\site-packages\hyrule_builder\unbuilder.py", line 265, in unbuild_mod
    _unbuild_actorinfo(mod, content, out)
  File "c:\python\lib\site-packages\hyrule_builder\unbuilder.py", line 120, in _unbuild_actorinfo
    output.write_text(oead.byml.to_text(actor), encoding="utf-8")
  File "c:\python\lib\pathlib.py", line 1240, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "c:\python\lib\pathlib.py", line 1208, in open
    opener=self._opener)
  File "c:\python\lib\pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP USER\\source\\repos\\BotW Actor Collision Generator .NET 5.0 - Async\\BotW Actor Collision Generator\\bin\\Debug\\net5.0-windows\\temp\\Build\\AirWallCreature_unbuilt\\content\\Actor\\ActorInfo\\DgnObj_DLC_IbutsuEx_BossBattleRoomDownloadTerminalBody_A_01.info.yml'
```

Said file does not exist, but the entry is present in **ActroInfo.product.sbyml**.
After this, I tried building it again without making any changes. And the following error occurred.

```
Failed to build content/Actor/ActorInfo/TwnObj_HyruleCastleObject_SwitchShutterFence_Iron_S_A_01.info.yml. [Errno 2] No such file or directory: 'build\\content\\Actor\\ActorInfo\\TwnObj_HyruleCastleObject_SwitchShutterFence_Iron_S_A_01.info'
```

This file does exist though, so I'm not sure what happened here.

**Comment by NiceneNerd** [comment]
My guess is that it's the Python limit on path name lengths. That's a pretty darn long path.

**Comment by ArchLeaders** [comment]
> My guess is that it's the Python limit on path name lengths. That's a pretty darn long path.

Ah, thank you! I will try a shorter path.

**Comment by ArchLeaders** [comment]
That was it, thanks!
