### ISSUE TITLE
Freezing on "Building AAMP and BYML files..."

### ISSUE THREAD

**Issue by ArchLeaders** [NiceneNerd/Hyrule-Builder#7]
Hey, it's me again.

So I'm trying to rebuild a bunch of actors and I'm having it freeze on "Building AAMP and BYML files...".

If I try and close the window, it does throw an error. 
Now, I think due to the odd format of the error shown that it's thrown multiple times over time, but suppressed until I try and close the window.

The output:

```
Removing old build...
Scanning source files...
Copying miscellaneous files...
Building AAMP and BYML files...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
```

At this time the "build" folder contents are re-encoded files. 

I tried running as admin, but it seems to just freeze. Pressing close the first time does nothing, the second terminating the console.

Thanks ~ Marcus

**Comment by ArchLeaders** [comment]
Update.

I left the cmd running in admin, and when I attempted to close the console it returned this error.

```
Removing old build...
Scanning source files...
Copying miscellaneous files...
Building AAMP and BYML files...
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
PermissionError: [WinError 5] Access is denied
```

**Comment by ArchLeaders** [comment]
My estimated summary of a single instance of the error.

Admin
```
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
```

Normal
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
```

**Comment by ArchLeaders** [comment]
Update.

I sorted the actors I was building alphabetically to narrow down what was causing the issue. After some more tests, I concluded that it was the "Merged_Grudge" actors.

I'm still unsure why, but it's progress.

**Comment by NiceneNerd** [comment]
Since the error seems to involve the multiprocessing module, try running the command with the `--single` flag to see what, if any, error occurs when running on a single process.

**Comment by ArchLeaders** [comment]
> Since the error seems to involve the multiprocessing module, try running the command with the `--single` flag to see what, if any, error occurs when running on a single process.

Alright, will do. Thanks!

**Comment by ArchLeaders** [comment]
With the command 
```
hyrule_builder build --single -b ".\HyRe_M"
```

It just aborted after `Building AAMP and BYML files...`, on verbose it aborted after
`Built content/Actor/ModelList/Mannequin_007_Lower.bmodellist.yml`.

**Comment by NiceneNerd** [comment]
Is there anything suspect in that file? If it's aborting so mysteriously it's probably triggering a bug on the C++ side of oead, which is hard to imagine w/o something wonky in the file itself.
